### PR TITLE
Add the "Rails 6 support" to the Changelog.

### PR DESCRIPTION
**Pull request by p8**
This updates the Changelog for a possible 0.3.2 release.

Is it possible to release a new version of the gem?

### CODE REVIEW

**Comment by senny** [comment]
Hi @p8 a release is possible but I have no app using this gem anymore to verify the current `master` is functional.

@siegy22 if you have this running in an app with Rails 6, please feel free to cut a release.

**Comment by p8** [comment]
@senny We’ve been running 3f1549e in production for a couple of months without problems.

**Comment by p8** [comment]
And thanks 😄

**Comment by senny** [comment]
Thanks @p8 

0.3.2 is out: https://rubygems.org/gems/pdfjs_viewer-rails/versions/0.3.2

please let me know if there is a problem.

**Comment by p8** [comment]
Thanks!

**Pull request merged**
